// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi80HW1VfaeHqb6gs_1Pupq0M36naxhAE',
    appId: '1:542276975400:web:d497e24db0932541f7ee1d',
    messagingSenderId: '542276975400',
    projectId: 'flutter3-60f66',
    authDomain: 'flutter3-60f66.firebaseapp.com',
    storageBucket: 'flutter3-60f66.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASgQ847Gs2cMdI6GUv23KrwAqMXy7RuLE',
    appId: '1:542276975400:android:5785457fc9fd7dd4f7ee1d',
    messagingSenderId: '542276975400',
    projectId: 'flutter3-60f66',
    storageBucket: 'flutter3-60f66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhnrkCs7w-e7fBG4j8-dBq4sp1zWSZNYA',
    appId: '1:542276975400:ios:f9bec34778396d37f7ee1d',
    messagingSenderId: '542276975400',
    projectId: 'flutter3-60f66',
    storageBucket: 'flutter3-60f66.appspot.com',
    iosClientId: '542276975400-osrhmfhv9oguifi0b574fnq480qr4vdt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
